networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  ui-service:
    build:
      context: .
      dockerfile: services/ui-service/Dockerfile
      target: development
    volumes:
      - ./services/ui-service:/app
      - ./shared:/app/shared
      - vscode-server:/home/vscode/.vscode-server
    ports:
      - "8501:8501"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8000
      - APP_ENV=development
      - LOG_LEVEL=INFO
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - api-gateway
    user: vscode
    networks:
      - frontend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
      target: development
    volumes:
      - ./api-gateway:/app
      - ./shared:/app/shared
      - vscode-server:/home/vscode/.vscode-server
      - ./logs:/app/logs
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    environment:
      - DOCUMENT_SERVICE_URL=http://document-service:8001
      - SEARCH_SERVICE_URL=http://search-service:8002
      - CHAT_SERVICE_URL=http://chat-service:8003
      - APP_ENV=development
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    user: vscode
    cap_add:
      - SYS_PTRACE    # Required for debugger
    security_opt:
      - seccomp:unconfined    # Required for debugger to attach to process
    networks:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - backend

  document-service:
    build:
      context: .
      dockerfile: services/document-service/Dockerfile
      target: development
    volumes:
      - ./services/document-service:/app
      - ./shared:/app/shared
      - vscode-server:/home/vscode/.vscode-server
      - ./logs:/app/logs
    ports:
      - "8001:8001"
      - "5679:5678"  # Debug port
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_ENV=development
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
    user: vscode
    cap_add:
      - SYS_PTRACE    # Required for debugger
    security_opt:
      - seccomp:unconfined    # Required for debugger to attach to process
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  search-service:
    build:
      context: .
      dockerfile: services/search-service/Dockerfile
      target: development
    volumes:
      - ./services/search-service:/app
      - ./shared:/app/shared
      - vscode-server:/home/vscode/.vscode-server
      - ./logs:/app/logs
    ports:
      - "8002:8002"
      - "5680:5678"  # Debug port
    environment:
      - APP_ENV=development
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
    user: vscode
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    cap_add:
      - SYS_PTRACE    # Required for debugger
    security_opt:
      - seccomp:unconfined    # Required for debugger to attach to process
    networks:
      - backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  chat-service:
    build:
      context: .
      dockerfile: services/chat-service/Dockerfile
      target: development
    volumes:
      - ./services/chat-service:/app
      - ./shared:/app/shared
      - vscode-server:/home/vscode/.vscode-server
      - ./logs:/app/logs
    ports:
      - "8003:8003"
      - "5681:5678"  # Debug port
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SEARCH_SERVICE_URL=http://search-service:8002
      - VECTOR_SERVICE_URL=http://vector-service:8004
      - APP_ENV=development
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    user: vscode
    cap_add:
      - SYS_PTRACE    # Required for debugger
    security_opt:
      - seccomp:unconfined    # Required for debugger to attach to process
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    depends_on:
      - vector-service
      - search-service
    networks:
      - backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  vector-service:
    build:
      context: .
      dockerfile: services/vector-service/Dockerfile
      target: development
    volumes:
      - ./services/vector-service:/app
      - ./shared:/app/shared
      - vscode-server:/home/vscode/.vscode-server
      - vector_store:/app/vector_store
      - vector_backups:/app/backups
      - ./logs:/app/logs
    ports:
      - "8004:8004"
      - "5682:5678"  # Debug port
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTOR_STORE_PATH=/app/vector_store/store.pkl
      - BACKUP_PATH=/app/backups
      - APP_ENV=development
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
    user: vscode
    cap_add:
      - SYS_PTRACE    # Required for debugger
    security_opt:
      - seccomp:unconfined    # Required for debugger to attach to process
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  vector_store:
    name: advisor_vector_store
  vector_backups:
    name: advisor_vector_backups
  vscode-server:
    name: vscode-server
  redis-data:
    name: redis-data
